package:
  name: pyosv
  version: "0.0.35"

source:
  path: ./

build:
  number: 0
  script: "$PYTHON -m pip install ."
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - rasterio
    - scikit-learn
    - tqdm
    - matplotlib
    - scipy
    - cartopy
    - pyproj
    - pyqt5
    - netCDF4
    - pillow

test:
  imports:
    - pyosv

about:
  home: https://github.com/alessandrosebastianelli/opensv/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Python LaTeX Utils."
